# Generated by the IDP scaffolder from
# 1-platform-catalog/per-service/infra/capabilities/postgres.tf.tmpl
# Edit the template, not this file — it is regenerated.
#
# Deliberately no `locals` block: every capability a service requests renders
# into the SAME Terraform root module directory, and local value names must be
# unique within a module. Two capabilities each declaring `locals { tags = ... }`
# is a hard "Duplicate local value definition" error at terraform validate.
# Tags are inlined below instead, so each file stays self-contained.

module "postgres" {
  source = "git::https://github.com/ok-karthik/internal-developer-platform.git//4-platform-engineering/3-capability-modules/aws/postgres?ref=v1.2.0"

  team_name = "payments"
  app_name  = "checkout"
  env       = "dev"

  tags = {
    Team        = "payments"
    Service     = "checkout"
    Environment = "dev"
    Capability  = "postgres"
    ManagedBy   = "terraform"
  }
}
