# Generated by the IDP scaffolder from
# 1-platform-catalog/per-service/infra/capabilities/postgres.tf.tmpl
# Edit the template, not this file — it is regenerated.
#
# Deliberately no `locals` block: every capability a service requests renders
# into the SAME Terraform root module directory, and local value names must be
# unique within a module. Two capabilities each declaring `locals { tags = ... }`
# is a hard "Duplicate local value definition" error at terraform validate.
# Tags are inlined below instead, so each file stays self-contained. The same rule
# is why every data block below is named after the capability: `data "aws_region"
# "current"` in two capability files would collide the same way.
#
# Network placement is read at plan time from the SSM parameter catalog the cloud
# foundation publishes on every stack apply (PLAN.md Phase 18.1, Pattern A), never
# hardcoded. The module's vpc_id / subnet_ids default to empty, which silently creates
# NO security group and NO subnet group — the database would land in the account's
# default VPC and the mistake would only surface at `terraform apply`.

data "aws_region" "postgres" {}

data "aws_ssm_parameter" "postgres_vpc_id" {
  name = "/platform/dev/${data.aws_region.postgres.region}/vpc/id"
}

data "aws_ssm_parameter" "postgres_database_subnets" {
  name = "/platform/dev/${data.aws_region.postgres.region}/vpc/database_subnets"
}

module "postgres" {
  source = "git::https://github.com/ok-karthik/enterprise-aws-infrastructure.git//iac-modules-repo/data/postgres?ref=postgres-v2.0.0"

  team_name = "tenant-a"
  app_name  = "app-a"
  env       = "dev"

  vpc_id     = data.aws_ssm_parameter.postgres_vpc_id.value
  subnet_ids = split(",", data.aws_ssm_parameter.postgres_database_subnets.value)

  tags = {
    Team        = "tenant-a"
    Service     = "app-a"
    Environment = "dev"
    Capability  = "postgres"
    ManagedBy   = "terraform"
  }
}
